// <auto-generated />
using System;
using KOLOK_2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KOLOK_2.Migrations
{
    [DbContext(typeof(NewDbContext))]
    [Migration("20250613144508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KOLOK_2.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            BirthDate = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            ArtistId = 2,
                            BirthDate = new DateTime(1982, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            LastName = "Doe"
                        },
                        new
                        {
                            ArtistId = 3,
                            BirthDate = new DateTime(1983, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("KOLOK_2.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearCreated")
                        .HasColumnType("int");

                    b.HasKey("ArtworkId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Artwork");

                    b.HasData(
                        new
                        {
                            ArtworkId = 1,
                            ArtistId = 1,
                            Title = "Title 1",
                            YearCreated = 2021
                        },
                        new
                        {
                            ArtworkId = 2,
                            ArtistId = 2,
                            Title = "Title 2",
                            YearCreated = 2022
                        },
                        new
                        {
                            ArtworkId = 3,
                            ArtistId = 3,
                            Title = "Title 3",
                            YearCreated = 2023
                        });
                });

            modelBuilder.Entity("KOLOK_2.Models.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GalleryId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfArtworks")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExhibitionId");

                    b.HasIndex("GalleryId");

                    b.ToTable("Exhibition");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            EndDate = new DateTime(1999, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 1,
                            NumberOfArtworks = 2,
                            StartDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Title 1"
                        },
                        new
                        {
                            ExhibitionId = 2,
                            EndDate = new DateTime(1999, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 2,
                            NumberOfArtworks = 2,
                            StartDate = new DateTime(1999, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Title 2"
                        },
                        new
                        {
                            ExhibitionId = 3,
                            EndDate = new DateTime(1999, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 3,
                            NumberOfArtworks = 2,
                            StartDate = new DateTime(1999, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Title 3"
                        });
                });

            modelBuilder.Entity("KOLOK_2.Models.ExhibitionArtwork", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<decimal>("InsuranceValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric");

                    b.HasKey("ExhibitionId", "ArtworkId");

                    b.HasIndex("ArtworkId");

                    b.ToTable("Exhibition_Artwork");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            ArtworkId = 2,
                            InsuranceValue = 15m
                        },
                        new
                        {
                            ExhibitionId = 2,
                            ArtworkId = 2,
                            InsuranceValue = 16m
                        },
                        new
                        {
                            ExhibitionId = 3,
                            ArtworkId = 3,
                            InsuranceValue = 17m
                        });
                });

            modelBuilder.Entity("KOLOK_2.Models.Gallery", b =>
                {
                    b.Property<int>("GalleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalleryId"));

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GalleryId");

                    b.ToTable("Galleries");

                    b.HasData(
                        new
                        {
                            GalleryId = 1,
                            EstablishedDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gallery 1"
                        },
                        new
                        {
                            GalleryId = 2,
                            EstablishedDate = new DateTime(1999, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gallery 2"
                        },
                        new
                        {
                            GalleryId = 3,
                            EstablishedDate = new DateTime(1999, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gallery 3"
                        });
                });

            modelBuilder.Entity("KOLOK_2.Models.Artwork", b =>
                {
                    b.HasOne("KOLOK_2.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("KOLOK_2.Models.Exhibition", b =>
                {
                    b.HasOne("KOLOK_2.Models.Gallery", "Gallery")
                        .WithMany("Exhibitions")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("KOLOK_2.Models.ExhibitionArtwork", b =>
                {
                    b.HasOne("KOLOK_2.Models.Artwork", "Artwork")
                        .WithMany("Exhibitions")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOLOK_2.Models.Exhibition", "Exhibition")
                        .WithMany("ExhibitionArtwork")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("KOLOK_2.Models.Artist", b =>
                {
                    b.Navigation("Artworks");
                });

            modelBuilder.Entity("KOLOK_2.Models.Artwork", b =>
                {
                    b.Navigation("Exhibitions");
                });

            modelBuilder.Entity("KOLOK_2.Models.Exhibition", b =>
                {
                    b.Navigation("ExhibitionArtwork");
                });

            modelBuilder.Entity("KOLOK_2.Models.Gallery", b =>
                {
                    b.Navigation("Exhibitions");
                });
#pragma warning restore 612, 618
        }
    }
}
